name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: "8.0.x"
      # You can test your matrix by printing the current dotnet version
    - name: Display dotnet version
      run: dotnet --version
    
    - name: create dotnet
      run:  dotnet build

    - name: install npm in the DotnetTemplate.Web 
      run: npm install
      working-directory: DotnetTemplate.Web

    - name: execute DotnetTemplate.Web directory
      run: npm run build
      working-directory: DotnetTemplate.Web
          
    - name: create dotnet test 
      run:  dotnet build
      working-directory: DotnetTemplate.Web

    - name: run npm inside dotnet
      run: npm t
      working-directory: DotnetTemplate.Web/Scripts/spec

    - name: run npm run lint
      run: npm run lint
      working-directory: DotnetTemplate.Web